# Kaggle's Titanic DataSet

### Lets import some libraries

In [6]:
import pandas as pd
import seaborn as sbn
import matplotlib as mpl
import logging as lg

### Now, we'll import our training dataset

First things firts, the documentation and general data for this dataset is published by Kaggle in the next link:

- https://www.kaggle.com/competitions/titanic/data?select=test.csv


And reading about this dataset, we can assume/infer this things:

* We already have a train and test dataset
* We already have the target variable ( `survival`)
* There are some categorical columns, for example: `pclass`, `sex`, `cabin` & `embark`
* Some numerical columns are present too

So, now we need to load our dataset and start searching for patterns and what ifs...

In [5]:
# We'll load the train dataset and see the first 10 registers

train_df = pd.read_csv('Data/titanic_train.csv')
train_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

And we noticed that there are some missing values (in `cabin`, for example), there are some out-of-patterns ticket numbers, full names, etc...

So, we'll start with some null and NaN analysis.

### Missing values & null values

In [11]:
# Missing values function: it receives a DataFrame and outputs another DataFrame

def missing_values_report(df: pd.DataFrame) -> pd.DataFrame:

    return (
        pd.DataFrame({
            "Count of missing values": df.isna().sum(),
            "Percent of missing values": (df.isna().sum() / len(df) * 100).round(1),
        })
    )

In [12]:
missing_values_report(train_df)

             Count of missing values  Percent of missing values
PassengerId                        0                        0.0
Survived                           0                        0.0
Pclass                             0                        0.0
Name                               0                        0.0
Sex                                0                        0.0
Age                              177                       19.9
SibSp                              0                        0.0
Parch                              0                        0.0
Ticket                             0                        0.0
Fare                               0                        0.0
Cabin                            687                       77.1
Embarked                           2                        0.2

And after seeing the results, we can deduce that the columns `age` and `Cabin` will present some problems if we take them as is.

I'll concentrate in the columns that have missing values.